---
stages:
  - check
  - build
  - test
  - doc
  - publish

workflow:
  name: 'Pipeline for branch: $CI_COMMIT_BRANCH'
  auto_cancel:
    on_new_commit: conservative

include:
  - project: "developers/v2/ci"
    ref: main
    file:
      - 'code_quality.yml'
    inputs:
      additional_args: "-vwarning"
      package: "rolly"
  - project: "developers/v2/ci"
    ref: main
    file:
      - 'cpp.yml'
    inputs:
      base_profile: "gcc14"
      package: "rolly"

format:
  extends: .check_formatting_template

code_quality:
  extends: .code_quality_template

build_linux_qt5:
  extends: .build_linux_template

build_linux_qt6:
  extends: .build_linux_qt6_template

test_linux:
  extends: .test_linux_template

test_linux_qt6:
  extends: .test_linux_qt6_template

publish_linux:
  extends: .publish_linux_template

documentation:
  tags: [ dev-utils ]
  stage: doc
  allow_failure: true
  script:
    - echo $CI_COMMIT_BRANCH
    - git fetch origin main:refs/remotes/origin/main --tags --force
    - cd .doc
    - poxy # --verbose --git-tags --min-version 2.2.0
    - mkdir -p ../public
    - cp -r html/* ../public
  artifacts:
    paths:
      - public

pages:
  tags: [ alse ]
  stage: doc
  allow_failure: true
  needs:
    - job: documentation
      artifacts: true
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public