---
stages:
  - check
  - build
  - test
  - doc
  - publish

workflow:
  name: 'Pipeline for branch: $CI_COMMIT_BRANCH'
  auto_cancel:
    on_new_commit: conservative

include:
  - project: "developers/v2/ci"
    ref: main
    file:
      - 'cpp.yml'
    inputs:
      additional_args: "-vwarning"
      base_profile: "gcc14"
      package: "rolly"

build_linux_qt5:
  extends: .build_linux_template

build_linux_qt6:
  extends: .build_linux_qt6_template

test_linux:
  extends: .test_linux_template

test_linux_qt6:
  extends: .test_linux_qt6_template

publish_linux:
  extends: .publish_linux_template

publish_linux_qt6:
  extends: .publish_linux_qt6_template

build_windows_mingw_qt5:
  extends: .build_windows_qt5_template

pages:
  extends: .poxy_template